### ISSUE TITLE
v4 Collections cache is too persistent

### ISSUE THREAD

**Issue by pwinnski** [prologueapp/Prologue#167]
I foolishly refreshed my library while organizing books on the server, so I ended up with a few series that shouldn't be there. 

I updated the server, fixing the authors and removing the series, but there seems to be no way to remove them from Prologue. I've refreshed my library repeatedly, and the books now show up in the correctly series, but also still in the old incorrect series. When I load the book details page, I see both series for the books that ended up in a different series, and still see a series for the book that I ended up not having in a series at all. 

Related, the Collections page still shows the wrong author list, although the book details page is correct.

To avoid abstraction, here's a concrete example:

<img width="585" height="402" alt="Image" src="https://github.com/user-attachments/assets/b1796bda-3ecd-41e2-818d-32780136caa3" />

The "In Flames" is a remnant of bad metadata, I assume. More importantly, "Old Man's War - John Scalzi" no longer exists on the server. There is still a series "Old Man's War" which now correctly has all seven books, including these three, but that series also shows "In Flames and John Scalzi" even though none of the books are authored by "In Flames." 

<img width="585" height="206" alt="Image" src="https://github.com/user-attachments/assets/c8d79b5a-f72c-4a99-bff2-668a784e7308" />

Prologue believes this book belongs to two series, but the server shows only one:

<img width="221" height="200" alt="Image" src="https://github.com/user-attachments/assets/f7b505df-71b1-4366-8a71-8ca2ded1b822" />

The other series is left over from that time I foolishly refreshed my library while organizing books on the server.

I have around 40 books downloaded, or I'd just delete the library and re-add it to clear the cache. If that's the recommended fix, I can do it anyway, but I'll wait to hear.

**Comment by pwinnski** [comment]
With the new counts (thank you!), I can see that Prologue believes I have 32 collections with 258 books, while ABS reports 29 series with 234 books. So that's 3 phantom series with 24 phantom books, in addition to the phantom author. Sadly, one of them is new. Yesterday I finally got tired of a "Chief Inspector Gamache/Three Pines" series, so I shortened it, but of course both now show up in Prologue, bumping this up from 5 phantom books to 24. 

'Cache invalidation' is one of the remaining hard problems in computer science, so... good luck!

**Comment by lcharlick** [comment]
This _should_ be fixed in 10427. Let me know if whether it correctly deletes those 3 series.

**Comment by pwinnski** [comment]
It did delete the series! Now counts are all correct, although I note that I'm still seeing "In Flames and John Scalzi" even though none of the books have "In Flames" as an author. So something is still cached oddly somewhere. 

Possibly unrelated, something I just noticed is that when I pull down to refresh on the Books tab, it briefly shows "286 books" before quickly counting up to the correct "288 books."

**Comment by pwinnski** [comment]
Today's update (10435) resolves the spurious author issue, and now "Collections" seem to be perfect, at least the way I use them. 

Keep up the amazing work!
