### ISSUE TITLE
Unable to login to server as root

### ISSUE THREAD

**Issue by fauxpaux** [prologueapp/Prologue#29]
When trying to login as root, there is a "Decoding failed" error

![IMG_A16741B4052A-1](https://github.com/user-attachments/assets/e2f9354d-7b71-4e45-b17f-7896cca92622)

**Comment by lcharlick** [comment]
Thanks for reporting. This should be fixed in build 10007.

**Comment by Rustymage** [comment]
I'm on 4.0.0 (10073) and this is not fixed.

![image](https://github.com/user-attachments/assets/5072e329-d5e3-4386-8b9c-64a4e84e5f84)

I'm not on 10078 because of https://github.com/prologueapp/Prologue/issues/77

Thanks.
