### ISSUE TITLE
no libraries available in prologue with abs server

### ISSUE THREAD

**Issue by gh57gh** [prologueapp/Prologue#69]
So prologue showed my abs library just fine as long as I had only the one library on my abs server. As soon as I added a podcast library on abs, no abs libraries were available anymore in prologue. I know that podcasts are not supported but why are my other libraries not showing? Does prologue only support abs servers that have no podcast libraries at all?
![IMG_8512](https://github.com/user-attachments/assets/c204e026-5eae-4083-b1c8-f4a1840441e5)

**Comment by ScuttleSE** [comment]
Similar issue here I think. I have two libraries named Audiobooks and Podcasts.

Only the Audiobooks-library is visible, but choosing it shows no books.

**Comment by JoeSmartChicken** [comment]
Same behavior for myself, just spun up my Audiobookshelf server V2.16.2. Audiobooks has 5 books and Podcasts is empty. Cannot choose a library in Prologue 2024.4.0 (10028). Left feedback via TestFlight as well.

**Comment by JoeSmartChicken** [comment]
Additional Testing:
Deleted the most recent TestFlight and went back through each of the previous builds.
Same behavior, cannot choose a library with ABS V2.16.2

**Comment by JoeSmartChicken** [comment]
Just updated to the newly pushed Prologue beta and this issue persists. Left feedback and screenshot via both the app and TestFlight. To have a broken functionality like this is a bad look, even for a beta version.

**Comment by ScuttleSE** [comment]
Can confirm. On the latest beta (v4.0.0 10040) and no libraries or books are visible
![image](https://github.com/user-attachments/assets/56c73072-81bb-47a3-a1bc-006dab9cb051)
![image](https://github.com/user-attachments/assets/3a9514ec-f250-40f8-8c26-a63de463ee7d)

**Comment by pjope** [comment]
I don't have the issue with the newest beta release. Everything works as expected.

**Comment by ScuttleSE** [comment]
> I don't have the issue with the newest beta release. Everything works as expected.

How do you connect to your ABS instance?

I have it behind a reverse proxy and publicly accessible on the internet, SSL cert and with an option for Oauth login.

**Comment by pjope** [comment]
Same for me, public available domain. In using traefik as a reverse proxy and an option for oauth. 

Worth mentioning is I'm on iOS 18.2 (22C5125e). 

ABS is on version 2.16.2

**Comment by ScuttleSE** [comment]
Same setup as me then, except I use Caddy as reverse proxy. How many libraries? I have one for audiobooks and one for podcasts. The podcast one doesn’t show up in Prologue though

**Comment by pjope** [comment]
I've just one library. This might be the difference 🤔

**Comment by JoeSmartChicken** [comment]
Updated to Prologue 2024.4.0 (10070) with Audiobookshelf at V2.17.2 and still encounter this issue. Collected screenshots and sent to the developer.

iPhone 16 Pro Max with iOS 18.1.1

**Comment by JoeSmartChicken** [comment]
Updated to Prologue 2024.4.0 (10078) with Audiobookshelf at V2.17.2 and still encounter this issue. Collected screenshots and sent to the developer. Unknown if it’s because I’m logging into ABS with just http. Tried with htttps and Prologue wouldn’t connect.

iPhone 16 Pro Max with iOS 18.2
iPad Pro 12.9” M1 with iPadOS 18.3 Public Beta
iPad mini 6th gen with iPadOS 18.3 Public Beta

**Comment by ScuttleSE** [comment]
I keep checking with every new beta. Still the same error; no books at all visible...

**Comment by 11qu1d** [comment]
Just stumbled upon the same issue. After setting up Podcasts in ABS, Prologue stopped showing the Audiobooks library (on refresh). After deleting Podcasts, the Audiobooks library became available again.

**Comment by gh57gh** [comment]
Yes, the problem still persists. Maybe the developer could give some insight into this problem and if it's even planned to be fixed.

**Comment by flintstones-fred** [comment]
Stumbled across the same issue. ABS server is only locally available. It is detected in prologue and let's do me a local authentication. But no libraries found. I have three libraries, one for Audiobooks, one for Podcasts, and one for Ebooks. I wish Prologue supports both Audiobooks and Podcasts, but even if the developer decides to not support Podcasts, this needs to be fixed so that users can still maintain multiple libraries in their ABS instance.

**Comment by tylerhunt** [comment]
The issue is definitely caused by multiple libraries being available. If you edit the user permissions to only allow a single library, it shows up fine in Prologue, but if more than one library is selected, Prologue shows no libraries are available.

**Comment by lcharlick** [comment]
Sorry, I completely missed this discussion. There were a few (or more) months there where I was in a bad place and wasn't working on the app at all. 

That said, this should be fixed as of a month or so ago. It was only an issue for servers that had one or more podcast libraries, which is why I didn't catch it originally.

**Comment by ScuttleSE** [comment]
Can confirm, works fine now! I have one Audiobook and one Podcast library. The audiobook-library shows up and plays back fine.

**Comment by thimplicity** [comment]
@lcharlick - I am still having the issue - I have 3 podcast and 3 audiobook libraries on the server. No librariey can be chosen

**Comment by lcharlick** [comment]
@thimplicity can you please send me logs from Settings > Report an Issue? Thanks.

**Comment by thimplicity** [comment]
@lcharlick done
